embed=discord.Embed(title="Harvard University", url="http://college.harvard.edu/admissions/application-process/application-requirements", color=0x20dfaf)
embed.set_thumbnail(url="https://iconape.com/wp-content/files/dx/67309/svg/harvard-university.svg")
embed.add_field(name="Acceptance Rate", value="5%", inline=False)
embed.add_field(name="Application Deadline", value="January 1", inline=True)
embed.add_field(name="SAT Range", value="1460-1580", inline=True)
embed.add_field(name="Application Fee", value="$75", inline=True)
embed.add_field(name="Application Website", value="college.harvard.edu", inline=True)
embed.add_field(name="International student acceptence rate", value="24.8%", inline=True)
embed.add_field(name="Early action deadline", value="1-Nov", inline=True)
embed.add_field(name="Undergrad percent international students", value="2.00%", inline=True)
embed.add_field(name="Early decision deadline", value="-", inline=True)
embed.add_field(name="International students receiving aid", value="75", inline=True)
embed.add_field(name="Percent of int'l students receiving aid", value="54.0%", inline=True)
await self.bot.say(embed=embed)